# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb73fcd5435557cf759ce9bb9ee576335d2ae96e3060b29159346fbfbf6b03e7d53b05e02c985dbb4c33874073dde2d52a5ac27d202ab2cc011a46a977937470

test:
  secret_key_base: 499e6a7305b1458f15c1f9217f000bc19dcb25537356d56cd973fe894644268cd2fd2db40129ae47479729cab0bc985087bf9f6fd8b8ee98a81c5771f0ba60a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
